#!/usr/bin/env bash

export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init - --no-rehash)"


# 移除gem默认源，改成ruby-china源
gem sources --add https://mirrors.tuna.tsinghua.edu.cn/rubygems/ --remove https://rubygems.org/
gem install bundler:2.4.4

# # 使用Gemfile和Bundle的项目，可以做下面修改，就不用修改Gemfile的source
# bundle config mirror.https://rubygems.org https://mirrors.tuna.tsinghua.edu.cn/rubygems
# # 删除Bundle的一个镜像源
# bundle config --delete 'mirror.https://rubygems.org'